include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.mocks.dart"
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
    invalid_annotation_target: ignore
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    prefer_single_quotes: true
    directives_ordering: false
    prefer_double_quotes: false
    always_use_package_imports: false
    sort_constructors_first: false
    library_private_types_in_public_api: false
    avoid_dynamic_calls: false
    comment_references: false
    library_prefixes: false
    # use_key_in_widget_constructors: false
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    omit_local_variable_types: true
    # always_specify_types: false
    unnecessary_final: false
    public_member_api_docs: false
    prefer_expression_function_bodies: false
    avoid_classes_with_only_static_members: false
    lines_longer_than_80_chars: false
    prefer_relative_imports: true